### ISSUE TITLE
Monthly QC files (and even Realtime files)?

### ISSUE THREAD

**Issue by lgramer** [GenSci/NDBC#20]
Again, I was very happy to see this project started! One more question...

As far as I can tell, currently the NDBC package will read complete year's worth of quality-controlled data. I particularly want more up-to-data buoy data, e.g., right now in January 2021, I would like the QC'd data for Jan-Nov of 2020 for a particular, which are available from the NDBC Web site, even though the "final" 2020 QC'd data file is not yet. Is this supported, or planned for support. Ideally, I would even like to be able to merge the un-QC'd "Realtime" data file for the past 45 days into my final pandas DataFrame. Same question for those RT files - any plan to support?

**Comment by supermanzer** [comment]
The current implementation does read monthly QC'd files (relying on the serving of .txt files by NOAA).  But thanks for pointing out the edge case of getting individual months from the previous year in the period prior to the full year QC'd file being available

I attempted to grab the "real time" or most current summary data but after performing some comparisons once those measurements lined up with monthly QC'd data summaries it appeared the discrepancy was significant so I didn't move further.  

I may have restricted my investigation of this issue so I may take it back up.  Of course any contributions are also welcome.

**Comment by supermanzer** [comment]
Realtime file ingestion separated into Issue #21 as it represents a feature enhancement

**Comment by supermanzer** [comment]
Updated monthly URL kwargs to allow retrieval of past months in the previous year.
